name: CI - Linux

on: 
  push:
    paths-ignore:
    - 'README.md'
    - 'docs/'
  pull_request:
    paths-ignore:
    - 'README.md'
    - 'docs/'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: dotnet test -l console;verbosity=normal
